config/routes.rb
Rails.application.routes.draw do
  resources :municipes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/municipe.rb
class Municipe < ApplicationRecord
    has_one_attached :small_picture
    has_one_attached :large_picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[ show edit update ]

  # GET /municipes or /municipes.json
  def index
    @municipes = Municipe.all
  end

  # GET /municipes/1 or /municipes/1.json
  def show
  end

  # GET /municipes/new
  def new
    @municipe = Municipe.new
  end

  # GET /municipes/1/edit
  def edit
  end

  # POST /municipes or /municipes.json
  def create
    @municipe = Municipe.new(municipe_params)
    @address  = Address.new(address_params)

    respond_to do |format|
      if @municipe.save && @address.save
        format.html { redirect_to municipe_url(@municipe), notice: "Municipe was successfully created." }
        format.json { render :show, status: :created, location: @municipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipes/1 or /municipes/1.json
  def update
    respond_to do |format|
      if @municipe.update(municipe_params)
        format.html { redirect_to municipe_url(@municipe), notice: "Municipe was successfully updated." }
        format.json { render :show, status: :ok, location: @municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipe
      @municipe = Municipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def municipe_params
      params.require(:municipe)
      .permit( 
        :name, :cpf, :cns, :email, :birth_date, :phone, :status,  :small_picture, :large_picture 
      )
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address)
      .permit( 
        :street, :district, :cep, :city, :uf, :complement, :ibge_code 
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/municipes_helper.rb
module MunicipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MunicipeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/municipes/_form.html.erb
<%= form_with(model: municipe, local: true) do |form| %>
  <% if municipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(municipe.errors.count, "error") %> prohibited this municipe from being saved:</h2>

      <ul>
        <% municipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.number_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :cns %>
    <%= form.number_field :cns %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_select :birth_date %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="field">
    <%= form.label :small_avatar %>
    <%= form.file_field :small_avatar %>
  </div>

  <div class="field">
    <%= form.label :large_avatar %>
    <%= form.file_field :large_avatar %>
  </div>

  <!-- Address -->
  <h1>Endereço!</h1>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :uf %>
    <%= form.text_field :uf %>
  </div>

  <div class="field">
    <%= form.label :complement %>
    <%= form.text_field :complement %>
  </div>

  <div class="field">
    <%= form.label :ibge_code %>
    <%= form.text_field :ibge_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/municipes/edit.html.erb
<h1>Editing Municipe</h1>

<%= render 'form', municipe: @municipe %>

<%= link_to 'Show', @municipe %> |
<%= link_to 'Back', municipes_path %>

app/views/municipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Municipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpf</th>
      <th>Cns</th>
      <th>Email</th>
      <th>Birth date</th>
      <th>Phone</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @municipes.each do |municipe| %>
      <tr>
        <td><%= municipe.name %></td>
        <td><%= municipe.cpf %></td>
        <td><%= municipe.cns %></td>
        <td><%= municipe.email %></td>
        <td><%= municipe.birth_date %></td>
        <td><%= municipe.phone %></td>
        <td><%= municipe.status %></td>
        <td><%= link_to 'Show', municipe %></td>
        <td><%= link_to 'Edit', edit_municipe_path(municipe) %></td>
        <td><%= link_to 'Destroy', municipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Municipe', new_municipe_path %>

app/views/municipes/new.html.erb
<h1>New Municipe</h1>

<%= render 'form', municipe: @municipe %>

<%= link_to 'Back', municipes_path %>

app/views/municipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @municipe.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @municipe.cpf %>
</p>

<p>
  <strong>Cns:</strong>
  <%= @municipe.cns %>
</p>

<p>
  <strong>Email:</strong>
  <%= @municipe.email %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @municipe.birth_date %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @municipe.phone %>
</p>

<p>
  <strong>Status:</strong>
  <%= @municipe.status %>
</p>

<%= link_to 'Edit', edit_municipe_path(@municipe) %> |
<%= link_to 'Back', municipes_path %>